name: Test and Upload Python Package

on:
  release:
    types: [published, prereleased]
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest --cov=lazy_ninja --cov-report=term-missing

  release-build:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'release'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Check version before build
        run: cat pyproject.toml | grep version

      - name: Clean previous builds
        run: rm -rf dist/*

      - name: Build release distributions
        run: |
          python -m pip install build
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs: release-build
    if: github.event_name == 'release'
    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/lazy-ninja

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Check version before publishing
        run: ls -lah dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/